config/routes.rb
Icteach::Application.routes.draw do
  resources :microposts

  resources :profs

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :prof_id
  belongs_to :user
  validates :content, :length => { :maximum => 140 }
end

app/models/prof.rb
class Prof < ActiveRecord::Base
  attr_accessible :email, :name
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, :notice => 'Micropost was successfully created.' }
        format.json { render :json => @micropost, :status => :created, :location => @micropost }
      else
        format.html { render :action => "new" }
        format.json { render :json => @micropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, :notice => 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @micropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profs_controller.rb
class ProfsController < ApplicationController
  # GET /profs
  # GET /profs.json
  def index
    @profs = Prof.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @profs }
    end
  end

  # GET /profs/1
  # GET /profs/1.json
  def show
    @prof = Prof.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @prof }
    end
  end

  # GET /profs/new
  # GET /profs/new.json
  def new
    @prof = Prof.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @prof }
    end
  end

  # GET /profs/1/edit
  def edit
    @prof = Prof.find(params[:id])
  end

  # POST /profs
  # POST /profs.json
  def create
    @prof = Prof.new(params[:prof])

    respond_to do |format|
      if @prof.save
        format.html { redirect_to @prof, :notice => 'Prof was successfully created.' }
        format.json { render :json => @prof, :status => :created, :location => @prof }
      else
        format.html { render :action => "new" }
        format.json { render :json => @prof.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /profs/1
  # PUT /profs/1.json
  def update
    @prof = Prof.find(params[:id])

    respond_to do |format|
      if @prof.update_attributes(params[:prof])
        format.html { redirect_to @prof, :notice => 'Prof was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @prof.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /profs/1
  # DELETE /profs/1.json
  def destroy
    @prof = Prof.find(params[:id])
    @prof.destroy

    respond_to do |format|
      format.html { redirect_to profs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/profs_helper.rb
module ProfsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Icteach</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :prof_id %><br />
    <%= f.number_field :prof_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Prof</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.prof_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>Prof:</b>
  <%= @micropost.prof_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/profs/_form.html.erb
<%= form_for(@prof) do |f| %>
  <% if @prof.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prof.errors.count, "error") %> prohibited this prof from being saved:</h2>

      <ul>
      <% @prof.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profs/edit.html.erb
<h1>Editing prof</h1>

<%= render 'form' %>

<%= link_to 'Show', @prof %> |
<%= link_to 'Back', profs_path %>

app/views/profs/index.html.erb
<h1>Listing profs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profs.each do |prof| %>
  <tr>
    <td><%= prof.name %></td>
    <td><%= prof.email %></td>
    <td><%= link_to 'Show', prof %></td>
    <td><%= link_to 'Edit', edit_prof_path(prof) %></td>
    <td><%= link_to 'Destroy', prof, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prof', new_prof_path %>

app/views/profs/new.html.erb
<h1>New prof</h1>

<%= render 'form' %>

<%= link_to 'Back', profs_path %>

app/views/profs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @prof.name %>
</p>

<p>
  <b>Email:</b>
  <%= @prof.email %>
</p>


<%= link_to 'Edit', edit_prof_path(@prof) %> |
<%= link_to 'Back', profs_path %>